
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: sistema_de_enquetes
  username: postgres  
  password: 123
  host: localhost          
  port: 5432 
  
test:
  <<: *default
  database: sistema_de_enquetes
  username: postgres       
  password: 123 
  host: localhost          
  port: 5432  

production:
  primary: &primary_production
    <<: *default
    database: sistema_de_enquetes_production
    username: sistema_de_enquetes
    password: 123
  cache:
    <<: *primary_production
    database: sistema_de_enquetes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sistema_de_enquetes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sistema_de_enquetes_production_cable
    migrations_paths: db/cable_migrate
